spring.application.name=user-service
service.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/energy_tracker
spring.datasource.username=energy-tracker
spring.datasource.password=San2004$

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=none

